---
title: "Latihan Modul 3 & 4"
author: "123200102_Muhammad Dzaki"
date: '`r Sys.Date()`'
output:
html_document: default
---

## Modul 3

meload library yang dibutuhkan
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r loading-libs, message=FALSE}
library(tibble)
library(dslabs)
data("murders")
```
## Nomor 1
```{r}
str(murders)
as_tibble(murders)
```
## Nomor 2
```{r}
names(murders)
```
## Nomor 3
```{r}
 a = murders$abb
 as_tibble(a)
 class(a)
```
## Nomor 4
```{r}
 b = murders$abb[7]
 as_tibble(b)
 class(b)
```
## Nomor 5
```{r}
  levels(murders$region)
  length(murders$region)
```
## Nomor 6
```{r}
  table(murders$state, murders$region)
```

## Modul 4
## Nomor 1
```{r}
  pop = murders$population
  sort(pop)
  pop[1]
```
## Nomor 2
```{r}
  y = order(murders$population)
  print(y[1])
```
## Nomor 3
```{r}
  which.min(murders$population)
```
## Nomor 4
```{r}
  murders$state[which.min(murders$population)]
```
## Nomor 5
```{r}
  ranks <- rank(murders$population)
  my_df = data.frame(state = murders$state, peringkat = ranks)
  my_df
```
## Nomor 6
```{r}
  ranks <- rank(murders$population)
  my_df = data.frame(state = murders$state, peringkat = ranks)
  ind = my_df[order(my_df$peringkat),]
  ind
```
## Nomor 7
```{r}
  population_in_millions <- log10(murders$population)
  total_gun_murders <- murders$total
  plot(population_in_millions, total_gun_murders)
```
## Nomor 8
```{r}
  population_in_millions = log10(murders$population)
  hist(population_in_millions, main="histogram of state population")
```
## Nomor 9
```{r}
  murders$boxplot <- with(murders, log10(population))
  boxplot(boxplot~region, data = murders)
```